// Turn src/bookmarklet/grabTracklist.js into a one-line `javascript:` URL that
// the Mixes tab can offer as a draggable link.
//
// It has to be inlined: a bookmarklet that fetched its body from
// http://localhost:8000 would be mixed content on an https:// page and get
// blocked, so the whole capture ships inside the URL.
//
// Generated into src/bookmarklet/generated.js (gitignored-adjacent but
// committed, so a clean checkout builds without running this first). Re-run
// with `npm run bookmarklet` after editing the source.
import esbuild from "esbuild";
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const SRC = resolve(here, "../src/bookmarklet/grabTracklist.js");
const OUT = resolve(here, "../src/bookmarklet/generated.js");

const { code } = await esbuild.transform(readFileSync(SRC, "utf8"), {
  minify: true,
  target: "es2017",
  loader: "js",
});

// Percent-encoded, not a raw string: a bookmarklet lives in an href, and a
// stray `"` or `#` in the source would truncate it silently. encodeURI plus `#`
// rather than encodeURIComponent: the latter also escapes `;` `,` `=` `:` `/`,
// which are legal in a URL and are most of minified JS — it cost ~15% of the
// length, and browsers stop honouring bookmarklets somewhere past ~8KB.
const url = "javascript:" + encodeURI(code.trim()).replace(/#/g, "%23");

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(
  OUT,
  "// GENERATED by scripts/buildBookmarklet.mjs — edit grabTracklist.js instead.\n" +
    "export const GRAB_BOOKMARKLET = " +
    JSON.stringify(url) +
    ";\n",
  "utf8",
);
console.log(`bookmarklet: ${url.length} chars -> src/bookmarklet/generated.js`);
